language: generic
sudo: required

services:
    - docker
before_install:
    - docker build -t ashboro/udemymulti -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true ashboro/udemymulti  npm test
  
after-success:
    - docker build -t ashboro/udemymulti-client ./client
    - docker build -t ashboro/udemymulti-nginx ./nginx
    - docker build -t ashboro/udemymulti-server ./server
    - docker build -t ashboro/udemymulti-worker ./worker
    # login to docker cli
    - echo "$DOCKER_PASSWORD" │ docker login -u "$DOCKER_ID" --password-stdin
    - docker push ashboro/udemymulti-client
    - docker push ashboro/udemymulti-nginx
    - docker push ashboro/udemymulti-server
    - docker push ashboro/udemymulti-worker
    # take out an push  >?<>>?:{@}~~}¬!""¬``¬





